services:    
    Parabol\DoctrineBehaviorsBundle\Reflection\ClassAnalyzer:

    parabol.class_analyzer:
        alias: Parabol\DoctrineBehaviorsBundle\Reflection\ClassAnalyzer

    Parabol\DoctrineBehaviorsBundle\Sortable\SortableListener:
        arguments: ["@parabol.class_analyzer", Parabol\DoctrineBehaviorsBundle\Sortable\SortableTrait, true]
        tags:
          - { name: doctrine.event_subscriber, connection: default }   